version: "3.9"

services:
  app:
    container_name: app
    image: app
    build:
      context: ./API
      dockerfile: Dockerfile
      target: runtime
    restart: always
    ports:
      - "5001:80"