version: "3"

services:
  app:
    container_name: app
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    ports:
      - "5001:80"
    networks:
      - app
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus_db:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app

  loki:
    image: grafana/loki:2.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - ./grafana_db:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app

networks:
  app: